name: ASCII Workflow with multiple jobs
on: push
jobs:
    build_job_1:
        runs-on: ubuntu-latest
        steps:
        - name: Install Cowsay program
          run: sudo apt-get install cowsay -y
        - name: Execute Cowsay program
          run: cowsay -f dragon "Run for cover, I am a DRAGON... RAWR" >> dragon.txt
        - name: Sleep for 30s
          run: sleep 30

    test_job_2:
        needs: build_job_1
        runs-on: ubuntu-latest
        steps:
        - name: Sleep for 10s
          run: sleep 10
        - name: Test file existance
          run: grep -i "dragon" dragon.txt

    deploy_job_3:
        needs: [build_job_1, test_job_2]
        runs-on: ubuntu-latest
        steps:
        - name: Read file
          run: cat dragon.txt
        - name: Deploy
          run: echo Deploying...
