name: My First Workflow
on: [push, fork]
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v4
          
        - name: Welcome to GitHub Actions
          run: echo "My first GitHub Actions workflow"

        - name: List files
          run: ls
        
        - name: Read file
          run: cat README.md

