name: Workflow filters and activities

on:
    push:
        # branches-ignore:
        #     - feature/*
        #     - test/**
        branches:
            - main
            - '!feature/*'
    workflow_dispatch:
    # schedule:
    #     - cron: "*/59 * * * *"
    pull_request:
        types:
            - opened
            - closed
        branches:
            - main
        paths-ignore: 
            - README.md

jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
            - name: Show the trigger event
              run: echo this workflow/job/step is executed for event type - ${{ github.event_name}}
